# Workflow to build the environment
name: ci
on: 
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
       - name: Checkout the repository on ubuntu runner
         uses: actions/checkout@v4
       - name: Install Java version 11
         uses: actions/setup-java@v4
         with:
           distribution: 'temurin' # See 'Supported distributions' for available options
           java-version: '11'
       - name: Build with Maven 
         run: |
           mvn package
           ls -l
       - name: upload the package
         uses: actions/upload-artifact@v4
         with:
           name: my-artifact
           path: target/devops.war
       
       - name: Set up QEMU
         uses: docker/setup-qemu-action@v3
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v3
       - name: Login to Docker Hub
         uses: docker/login-action@v3
         with:
           username: ${{ secrets.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_TOKEN }}
       - name: Build and push
         uses: docker/build-push-action@v5
         with:
           push: true
           tags: cloudsihmar/intel:latest
       
       
            
           
         
    
